application: bficalendar
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- admin_redirect: on

handlers:
- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /statics
  static_dir: statics

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /calendar/.*
  script: calhandlers.py

- url: .*
  script: main.py



